import os

import psycopg2
from psycopg2.extras import RealDictCursor


DATABASE_URL = os.getenv("DATABASE_URL")


class DatabaseConnection:
    """
    Small compatibility wrapper around psycopg2.

    This allows the rest of SOMA HUB to use:
        conn.execute(...)
        conn.commit()
        conn.rollback()
        conn.close()

    while PostgreSQL/Neon handles the actual database connection.
    """

    def __init__(self, connection):
        self._connection = connection

    def execute(self, query, params=None):
        cursor = self._connection.cursor()

        if params is None:
            cursor.execute(query)
        else:
            cursor.execute(query, params)

        return cursor

    def cursor(self):
        return self._connection.cursor()

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        if exc_type is not None:
            self.rollback()
        else:
            self.commit()

        self.close()

    def __getattr__(self, name):
        return getattr(self._connection, name)


def get_connection():
    if not DATABASE_URL:
        raise RuntimeError(
            "DATABASE_URL is not set. Add your Neon PostgreSQL connection string "
            "to the environment before starting the backend."
        )

    connection = psycopg2.connect(DATABASE_URL)

    return DatabaseConnection(connection)


def init_database():
    connection = get_connection()

    try:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS students (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                soma_hub_code TEXT NOT NULL UNIQUE,
                name TEXT NOT NULL,
                school_name TEXT,
                grade TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS admins (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                created_at TEXT NOT NULL
            )
            """
        )

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS term_points (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_id INTEGER NOT NULL,
                term_key TEXT NOT NULL,
                study_notes_points INTEGER NOT NULL DEFAULT 0,
                topical_quiz_points INTEGER NOT NULL DEFAULT 0,
                exam_points INTEGER NOT NULL DEFAULT 0,
                consistency_points INTEGER NOT NULL DEFAULT 0,
                improvement_points INTEGER NOT NULL DEFAULT 0,
                total_points INTEGER NOT NULL DEFAULT 0,
                FOREIGN KEY (student_id)
                    REFERENCES students(id)
                    ON DELETE CASCADE,
                UNIQUE(student_id, term_key)
            )
            """
        )

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS quiz_results (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_id INTEGER NOT NULL,
                material_id TEXT,
                material_title TEXT,
                subject TEXT,
                grade_key TEXT,
                quiz_type TEXT NOT NULL,
                score INTEGER NOT NULL,
                total INTEGER NOT NULL,
                percentage REAL NOT NULL,
                completed_at TEXT NOT NULL,
                FOREIGN KEY (student_id)
                    REFERENCES students(id)
                    ON DELETE CASCADE
            )
            """
        )

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS payment_sessions (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                session_id TEXT NOT NULL UNIQUE,
                student_id INTEGER NOT NULL,
                soma_hub_code TEXT NOT NULL,
                amount INTEGER NOT NULL,
                status TEXT NOT NULL DEFAULT 'PENDING',
                checkout_request_id TEXT,
                merchant_request_id TEXT,
                created_at TEXT NOT NULL,
                expires_at TEXT NOT NULL,
                completed_at TEXT,
                purpose TEXT,
                purpose_result TEXT,
                FOREIGN KEY (student_id)
                    REFERENCES students(id)
                    ON DELETE CASCADE
            )
            """
        )

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS mpesa_transactions (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                transaction_id TEXT NOT NULL UNIQUE,
                payment_session_id TEXT,
                student_id INTEGER NOT NULL,
                soma_hub_code TEXT NOT NULL,
                amount INTEGER NOT NULL,
                transaction_type TEXT,
                transaction_time TEXT,
                mpesa_phone TEXT,
                first_name TEXT,
                middle_name TEXT,
                last_name TEXT,
                status TEXT NOT NULL DEFAULT 'COMPLETED',
                created_at TEXT NOT NULL,
                FOREIGN KEY (student_id)
                    REFERENCES students(id)
                    ON DELETE CASCADE,
                FOREIGN KEY (payment_session_id)
                    REFERENCES payment_sessions(session_id)
                    ON DELETE SET NULL
            )
            """
        )

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS wallet_transactions (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_id INTEGER NOT NULL,
                soma_hub_code TEXT NOT NULL,
                amount INTEGER NOT NULL,
                transaction_type TEXT NOT NULL,
                reference TEXT,
                description TEXT,
                created_at TEXT NOT NULL,
                FOREIGN KEY (student_id)
                    REFERENCES students(id)
                    ON DELETE CASCADE
            )
            """
        )

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS coin_transactions (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_id INTEGER NOT NULL,
                soma_hub_code TEXT NOT NULL,
                amount INTEGER NOT NULL,
                transaction_type TEXT NOT NULL,
                reference TEXT NOT NULL UNIQUE,
                description TEXT,
                created_at TEXT NOT NULL,
                FOREIGN KEY (student_id)
                    REFERENCES students(id)
                    ON DELETE CASCADE
            )
            """
        )

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS material_unlocks (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_id INTEGER NOT NULL,
                soma_hub_code TEXT NOT NULL,
                material_id TEXT NOT NULL,
                coins_spent INTEGER NOT NULL DEFAULT 0,
                ksh_spent INTEGER NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL,
                UNIQUE (student_id, material_id),
                FOREIGN KEY (student_id)
                    REFERENCES students(id)
                    ON DELETE CASCADE
            )
            """
        )

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS subscriptions (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_id INTEGER NOT NULL,
                soma_hub_code TEXT NOT NULL,
                grade_key TEXT NOT NULL,
                starts_at TEXT NOT NULL,
                expires_at TEXT NOT NULL,
                ksh_paid INTEGER NOT NULL,
                reference TEXT NOT NULL UNIQUE,
                created_at TEXT NOT NULL,
                FOREIGN KEY (student_id)
                    REFERENCES students(id)
                    ON DELETE CASCADE
            )
            """
        )

        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_subscriptions_soma_code
            ON subscriptions(soma_hub_code)
            """
        )

        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_coin_transactions_soma_code
            ON coin_transactions(soma_hub_code)
            """
        )

        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_material_unlocks_soma_code
            ON material_unlocks(soma_hub_code)
            """
        )

        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_students_soma_hub_code
            ON students(soma_hub_code)
            """
        )

        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_term_points_student
            ON term_points(student_id)
            """
        )

        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_quiz_results_student
            ON quiz_results(student_id)
            """
        )

        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_payment_sessions_student
            ON payment_sessions(student_id)
            """
        )

        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_payment_sessions_soma_code
            ON payment_sessions(soma_hub_code)
            """
        )

        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_payment_sessions_status
            ON payment_sessions(status)
            """
        )

        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_mpesa_transactions_student
            ON mpesa_transactions(student_id)
            """
        )

        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_mpesa_transactions_soma_code
            ON mpesa_transactions(soma_hub_code)
            """
        )

        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_wallet_transactions_student
            ON wallet_transactions(student_id)
            """
        )

        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_wallet_transactions_soma_code
            ON wallet_transactions(soma_hub_code)
            """
        )

        connection.commit()

    except Exception:
        connection.rollback()
        raise

    finally:
        connection.close()


if __name__ == "__main__":
    init_database()
    print("SOMA HUB PostgreSQL database initialized successfully.")